### PR TITLE
argparse_vals_only just keeps the parameters we want.

### PR DESCRIPTION
**Pull request by zshaheen**

### CODE REVIEW

**Comment by doutriaux1** [comment]
thanks @zshaheen will take a look today.

**Comment by doutriaux1** [comment]
@zshaheen 

using:
```python
args = parser.get_parameters(cmd_default_vars=False, argparse_vals_only=True)[0]
```

Leads to the same error

using

```python
args = parser.get_parameters(cmd_default_vars=False, argparse_vals_only=False)[0]

print("ARGS:",args)
print("You picked: {}".format(args.charles))
print("Peter:", args.peter)
```

Leads to `peter` existing in args.

I'm not sure how to trigger your changes.

**Comment by zshaheen** [comment]
@doutriaux1 first, the parameter `argparse_vals_only` must be True. As [discussed here](https://github.com/PCMDI/pcmdi_metrics/issues/585#issuecomment-436832905), please confirm that you're using the correct version of cdp.

**Comment by doutriaux1** [comment]
@zshaheen you were right I had another old cdp installed in there, (not as an egg) and it wass picking this one rather than the one from the branch

**Comment by doutriaux1** [comment]
One thing though, if I do not pass a parameter, it's not using the `default` value

```python
import cdp
parser = cdp.cdp_parser.CDPParser()
parser.add_argument("--charles", default="DEFAULT")
args = parser.get_parameters(cmd_default_vars=False, argparse_vals_only=True)[0]
print("ARGS:",args)
print("You picked: {}".format(args.charles))
print("Peter:", args.peter)
```

gives:
```
(vcs) doutriaux1@loki:[~/CDP]:[46864]> python test_params.py 
ARGS: <cdp.cdp_parameter.CDPParameter object at 0x12399fe48>
Traceback (most recent call last):
  File "test_params.py", line 12, in <module>
    print("You picked: {}".format(args.charles))
AttributeError: 'CDPParameter' object has no attribute 'charles'
```

**Comment by zshaheen** [comment]
@doutriaux1 If you want to use the command line default values, those defined in `parser.add_argument()`, you need to set the `cmd_default_vars` to `True`.

Can you try this?

**Comment by zshaheen** [comment]
@doutriaux1 Here's the code I tested, I just set `cmd_default_vars` to `True`.
```python
import cdp
parser = cdp.cdp_parser.CDPParser()
parser.add_argument("--charles", default="DEFAULT")
args = parser.get_parameters(cmd_default_vars=True, argparse_vals_only=True)[0]
print("ARGS:",args)
print("You picked: {}".format(args.charles))
print("Peter:", args.peter)
```

This gets the default value:
```
(acme_diags_env_dev) shaheen2@shaheen2ml:~$ python charles_ex.py 
('ARGS:', <cdp.cdp_parameter.CDPParameter object at 0x110f4c110>)
You picked: DEFAULT
Traceback (most recent call last):
  File "charles_ex.py", line 7, in <module>
    print("Peter:", args.peter)
AttributeError: 'CDPParameter' object has no attribute 'peter'
```

Now setting `argsparse_vals_only` to `False` gets it working with the `peter` parameter:
```
(acme_diags_env_dev) shaheen2@shaheen2ml:~$ python charles_ex.py -p params.py 
('ARGS:', <cdp.cdp_parameter.CDPParameter object at 0x102831110>)
You picked: DEFAULT
('Peter:', 'this is peter')
```

**Comment by doutriaux1** [comment]
@zshaheen thanks I did try it to it and worked.

**Pull request merged**
