### PR TITLE
Allow selection of multiprocessing context

### PR DESCRIPTION
**Pull request by xylar**
This should help with some issues seen in e3sm_diags (https://github.com/E3SM-Project/e3sm_diags/issues/316) since dask switched from "fork" to "spawn" as the default context.

### CODE REVIEW

**Comment by xylar** [comment]
@zshaheen or @chengzhuzhang, are you able to review this?

**Comment by xylar** [comment]
## Testing

I did a test build of these changes using a modified version of the recipe from conda-forge, which I put in `recipe/meth.yaml`:
``` yaml
{% set name = "cdp" %}
{% set version = "1.6.1" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
    number: 0
    noarch: python
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"
    entry_points:
      - cdp-distrib = cdp.cli.cdp_distrib:main

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - output_viewer >=1.3.0
    - pyyaml
    - dask
    - distributed
    - six

test:
  imports:
      - cdp
  commands:
      - cdp-distrib -h

about:
  home: https://github.com/cdat/cdp
  summary: |
    The Community Diagnostics Package (CDP) is a framework for developing new
    climate diagnostics. CDP allows for a modular implementation of the
    components required for running diagnostics. The design of CDP consists
    of modules to handle the user-defined parameters, metrics, provenance,
    file I/O, output of results and algorithms for calculating the diagnostics.
  license: BSD-3-Clause
  license_file: bsd-3-clause.txt

extra:
    recipe-maintainers:
        - doutriaux1
        - zshaheen
        - xylar
```
Then, I ran `conda build` as usual:
```
conda build recipe
```
Then, I used it in a test environment for `e3sm_diags`:
```
conda create -y -n e3sm_diags_dev --use-local -c conda-forge -c defaults python=3.7 cdp=1.6.1 cdms2 cdutil genutil \
    cdtime numpy matplotlib cartopy beautifulsoup4 lxml dask
```
I installed `e3sm_diags` from my branch here:
https://github.com/xylar/e3sm_diags/tree/fix_multiprocessing
This is the same as in PR https://github.com/E3SM-Project/e3sm_diags/pull/339.
```
conda activate e3sm_diags_dev
pip install .
```
Then, I ran the example diagnostics on Cori using the run script supplied in the documentation:
https://e3sm-project.github.io/e3sm_diags/docs/html/quickguides/quick-guide-cori.html#config-and-run

``` python
#!/usr/bin/env python

import os
from acme_diags.parameter.core_parameter import CoreParameter
from acme_diags.run import runner

param = CoreParameter()

param.reference_data_path = '/global/cfs/cdirs/e3sm/acme_diags/obs_for_e3sm_diags/climatology/'
param.test_data_path = '/global/cfs/cdirs/e3sm/acme_diags/test_model_data_for_acme_diags/climatology/'
param.test_name = '20161118.beta0.FC5COSP.ne30_ne30.edison'
param.seasons = ["ANN"]   #all seasons ["ANN","DJF", "MAM", "JJA", "SON"] will run,if comment out"
 prefix = '/global/cfs/cdirs/e3sm/www/xylar/doc_examples_latest_dask/'
param.results_dir = os.path.join(prefix, 'lat_lon_demo')
# Use the following if running in parallel:
param.multiprocessing = True
param.num_workers = 32

# Use below to run all core sets of diags:
#runner.sets_to_run = ['lat_lon','zonal_mean_xy', 'zonal_mean_2d', 'polar', 'cosp_histogram', 'meridional_mean_2d']
# Use below to run lat_lon map only:
runner.sets_to_run = ['lat_lon']
runner.run_diags([param])
```

I did not see the errors reported in https://github.com/E3SM-Project/e3sm_diags/issues/316 that we had previously seen with the latest `dask`.

**Comment by chengzhuzhang** [comment]
This PR looks good to me. But we need to make sure the change won't affect `pmp` and need tests from `pmp` developers. And it would be helpful to get @zshaheen 's insight as well.

**Review by zshaheen — APPROVED** [review]
Looks good to me and it seems like `e3sm_diags` (and others) will work without any changes on their end. Thanks for doing this!

**Comment by xylar** [comment]
@chengzhuzhang, I agree that `pmp` should be tested.  Unless I've made a mistake, the default behavior after the change should be identical to before the change.

**Comment by chengzhuzhang** [comment]
@gleckler1 @lee1043 @durack1, Hi guys, I would like to draw your attention on this `cdp` PR. Like `e3sm_diags` has been using multiprocessing through CDP, and with `dask` switching from "fork" to "spawn" as the default context, we had issue to make multiprocssing work in `e3sm_diags`. [if `pmp` also had the same multiprocessing implementation, the same issue would also occur in `pmp`] @xylar made this PR to allow selection of multiprocessing context. Since `cdp` is also `pmp`'s dependency, I would like to check with you to make sure if this change won't break `pmp`. Please let me know if this PR is okay. Thanks!

**Comment by lee1043** [comment]
@chengzhuzhang thanks for checking with us. My part of multiprocessing is not relying in `cdp` as it is more like generating multiple subprocesses. However others in the PMP team may be more relavant. @gleckler1 uses `dask` in the mean climate metric calcuation, so I think his insight might be more helpful.

**Comment by gleckler1** [comment]
@xylar @chengzhuzhang @lee1043   We do use dask via the cdp in several cases.  On example is 
https://github.com/PCMDI/pcmdi_metrics/blob/65dfba825b88c26a3d8557d10591b7ed50dc8b5d/pcmdi_metrics/diurnal/scripts/compositeDiurnalStatistics.py#L234

Can someone advise on what we will need to do (if anything) to keep this working?

Many thanks for alerting us to this issue.

**Comment by chengzhuzhang** [comment]
Hi @gleckler1 , 

Thank you for pointing this out! In this example, It looks like @jasonb5 already took care of the multiprocessing error by added 
```
# Good practice to place contents of script under this check
if __name__ == '__main__':
    # Related to script being installed as executable
    mp.freeze_support()

    main()
```
at the end of the script with the commit https://github.com/PCMDI/pcmdi_metrics/commit/34c3eb6bc822ce30196e75f7a386711a74f7cadf

I suppose this PR won't break multiprocessing in PMP, but should test with PMP

**Comment by chengzhuzhang** [comment]
@glecker1 Hi Peter, I need to merge this PR so that the new release of e3sm-diags will be compatible with the latest dask. With the comment above, I think PMP will work without glitch with this PR. I will ask CDAT team to merge if it is okay with you.

**Comment by gleckler1** [comment]
@chengzhuzhang Hi Jill.  Apologies for the delay on my end.   Can you give me 24hrs to run a few tests?
P

**Comment by chengzhuzhang** [comment]
@gleckler1 Absolutely. Let me know if there are any problems. Thanks for working on this!

**Comment by chengzhuzhang** [comment]
@gleckler1 Hi Peter, any update? if it is difficult to test now. We could go ahead and have a release now and you can let me know if the new version works at a later time?

**Comment by gleckler1** [comment]
@chengzhuzhang  OK.  I will try with updated cdp when I return in about 2 weeks.

**Comment by chengzhuzhang** [comment]
Sounds good, @gleckler1, thank you. 
@forsyth2, Hi Ryan, do you have write access to this repo? If so, would you please merge this PR and make a new release?

**Pull request merged**
